version: 2
jobs:
  build:
    branches:
      only:
        - master
    docker:
      - image: cibuilds/hugo:latest
    steps:
      - checkout
      - run: hugo
      - run: cd public && git add --all && git commit -m "Publishing to gh-pages" && cd ..
